services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app-php
    restart: always
    user: 'www-data:www-data'
    working_dir: /home/app
    volumes:
      - ./:/home/app
  nginx:
    image: nginx:1.19-alpine
    container_name: app-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/home/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf